import argparse
import json
from datetime import datetime

from app.config import settings
from core.character_bible import CharacterBibleGenerator
from core.final_package import FinalPackageError, FinalProjectPackager
from core.image_generator import ImageGenerator
from core.music_generator import ProceduralMusicGenerator
from core.project import StoryProject
from core.scene_planner import ScenePlanner
from core.script_writer import ScriptWriter
from core.seo_generator import YouTubeMetadataGenerator
from core.sfx_generator import ProceduralSFXGenerator
from core.story_generator import StoryGenerator
from core.thumbnail_generator import ThumbnailGenerator
from core.tts_generator import NarrationGenerator
from core.video_renderer import VideoRenderer


def main() -> None:
    parser = argparse.ArgumentParser(description="AI YouTube Stories — complete local pipeline")
    parser.add_argument("topic", help="Seed or idea for the original story")
    parser.add_argument("--minutes", type=int, default=30)
    parser.add_argument("--project", default=None)
    parser.add_argument("--no-tts", action="store_true")
    parser.add_argument("--no-images", action="store_true", help="Skip local AI image generation")
    parser.add_argument("--no-music", action="store_true", help="Skip procedural background music")
    parser.add_argument("--no-sfx", action="store_true", help="Skip procedural SFX")
    parser.add_argument("--no-render", action="store_true")
    parser.add_argument("--package", action="store_true")
    args = parser.parse_args()

    if not 10 <= args.minutes <= 120:
        parser.error("--minutes must be between 10 and 120")

    story = StoryGenerator().generate(args.topic, args.minutes)
    print(f"\nІСТОРІЯ: {story.title}\nЖАНР: {story.genre}\nЛОГЛАЙН: {story.logline}\n")

    print("Створюю Character Bible...")
    character_bible = CharacterBibleGenerator().generate(story)
    script = ScriptWriter().write(story, args.minutes)

    print("Створюю режисерський план сцен...")
    scene_plan = ScenePlanner().plan(story, script, args.minutes)
    print(f"Сцен: {len(scene_plan.scenes)} | орієнтовно {scene_plan.total_duration_seconds / 60:.1f} хв")

    project_id = args.project or datetime.now().strftime("story_%Y%m%d_%H%M%S")
    project = StoryProject().create(story, script, project_id, scene_plan, character_bible.model_dump())

    if not args.no_images:
        print("\n🎨 Генерую AI-зображення сцен...")
        ImageGenerator().generate(scene_plan, character_bible, project / "images")
    else:
        print("\n⏭ Зображення пропущено (--no-images)")

    if not args.no_tts:
        print("\n🎙 Створюю українську озвучку через FilmDubUA/Piper...")
        narration = NarrationGenerator().generate(scene_plan, project / "audio", settings.filmdubua_voice_profile, settings.tts_rate, settings.tts_volume)
        (project / "narration.json").write_text(json.dumps(narration.model_dump(), ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"Озвучено: {len(narration.segments)} сцен, {narration.total_duration_seconds / 60:.1f} хв")
    else:
        print("\n⏭ Озвучку пропущено (--no-tts)")

    if not args.no_music:
        print("\n🎵 Створюю оригінальну процедурну музику...")
        music = ProceduralMusicGenerator().generate(max(1, scene_plan.total_duration_seconds), project / "music")
        (project / "music" / "music_manifest.json").write_text(json.dumps({"provider": "procedural_local", "file": music.name, "license": "originally generated by this project"}, ensure_ascii=False, indent=2), encoding="utf-8")

    if not args.no_sfx:
        sfx = ProceduralSFXGenerator().generate_hit(project / "sfx")
        (project / "sfx" / "sfx_manifest.json").write_text(json.dumps({"provider": "procedural_local", "file": sfx.name, "license": "originally generated by this project"}, ensure_ascii=False, indent=2), encoding="utf-8")

    first_image = project / "images" / "scene_001.png"
    if first_image.exists():
        print("\n🖼 Створюю thumbnail...")
        ThumbnailGenerator().generate(story.title, first_image, project / "thumbnail")

    print("\n🔎 Створюю YouTube SEO...")
    YouTubeMetadataGenerator().generate(story, project / "youtube")

    if not args.no_render and not args.no_tts:
        print("\n🎬 Збираю фінальне MP4 через FFmpeg...")
        music_files = sorted(project.joinpath("music").glob("*.wav"))
        output = VideoRenderer(settings.ffmpeg_bin, settings.output_fps, settings.video_width, settings.video_height).render(
            scene_plan, project, music_file=music_files[0] if music_files else None
        )
        print(f"Фінальне відео: {output}")
    else:
        print("\n⏭ Рендер пропущено")

    require_video = not args.no_render and not args.no_tts
    packager = FinalProjectPackager()
    report = packager.validate(project, require_video=require_video)
    manifest = packager.write_manifest(project, report)
    print(f"\n📦 Маніфест: {manifest}")

    if args.package:
        try:
            archive = packager.package(project, require_video=require_video)
            print(f"ZIP-пакет: {archive}")
        except FinalPackageError as exc:
            print(f"\n⛔ ZIP не створено: {exc}")
    elif report["valid"]:
        print("Проєкт пройшов фінальну перевірку. Для ZIP використай --package.")
    else:
        print("Проєкт ще не готовий:")
        for item in report["missing"]:
            print(f"  - {item}")

    print(f"\nГотово. Проєкт: {project}")


if __name__ == "__main__":
    main()
